export const GET_PRODUCT_DATA_REQUEST = "GET_PRODUCT_DATA_REQUEST";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_FAILURE = "GET_PRODUCT_DATA_FAILURE";

export const ADD_CART_DATA_REQUEST=' ADD_CART_DATA_REQUEST';
export const ADD_CART_DATA_SUCCESS=' ADD_CART_DATA_SUCCESS';
export const ADD_CART_DATA_ERROR=' ADD_CART_DATA_ERROR';

export const GET_CART_DATA_REQUEST=' GET_CART_DATA_REQUEST';
export const GET_CART_DATA_SUCCESS=' GET_CART_DATA_SUCCESS';
export const GET_CART_DATA_ERROR=' GET_CART_DATA_ERROR';


export const DELETE_CART_DATA_REQUEST=' DELETE_CART_DATA_REQUEST';
export const DELETE_CART_DATA_SUCCESS=' DELETE_CART_DATA_SUCCESS';
export const DELETE_CART_DATA_ERROR=' DELETE_CART_DATA_ERROR';