export const GET_PRODUCT_DATA_REQUEST = "GET_PRODUCT_DATA_REQUEST";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_FAILURE = "GET_PRODUCT_DATA_FAILURE";

export const ADD_CART_DATA_REQUEST=' ADD_CART_DATA_REQUEST';
export const ADD_CART_DATA_SUCCESS=' ADD_CART_DATA_SUCCESS';
export const ADD_CART_DATA_ERROR=' ADD_CART_DATA_ERROR';

export const GET_CART_DATA_REQUEST=' GET_CART_DATA_REQUEST';
export const GET_CART_DATA_SUCCESS=' GET_CART_DATA_SUCCESS';
export const GET_CART_DATA_ERROR=' GET_CART_DATA_ERROR';


export const DELETE_CART_DATA_REQUEST=' DELETE_CART_DATA_REQUEST';
export const DELETE_CART_DATA_SUCCESS=' DELETE_CART_DATA_SUCCESS';
export const DELETE_CART_DATA_ERROR=' DELETE_CART_DATA_ERROR';

export const ADD_CHECKOUT_DATA_REQUEST=' ADD_CHECKOUT_DATA_REQUEST';
export const ADD_CHECKOUT_DATA_SUCCESS=' ADD_CHECKOUT_DATA_SUCCESS';
export const ADD_CHECKOUT_DATA_ERROR=' ADD_CHECKOUT_DATA_ERROR';

export const GET_CHECKOUT_DATA_REQUEST=' GET_CHECKOUT_DATA_REQUEST';
export const GET_CHECKOUT_DATA_SUCCESS=' GET_CHECKOUT_DATA_SUCCESS';
export const GET_CHECKOUT_DATA_ERROR=' GET_CHECKOUT_DATA_ERROR';

export const ADD_PAYMENT_DATA_REQUEST=' ADD_PAYMENT_DATA_REQUEST';
export const ADD_PAYMENT_DATA_SUCCESS=' ADD_PAYMENT_DATA_SUCCESS';
export const ADD_PAYMENT_DATA_ERROR=' ADD_PAYMENT_DATA_ERROR';

export const GET_PAYMENT_DATA_REQUEST=' GET_PAYMENT_DATA_REQUEST';
export const GET_PAYMENT_DATA_SUCCESS=' GET_PAYMENT_DATA_SUCCESS';
export const GET_PAYMENT_DATA_ERROR=' GET_PAYMENT_DATA_ERROR';

