// sign up-
export const REQUEST_SIGN_UP = "REQUEST_SIGN_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";
export const ERROR_SIGN_UP = "ERROR_SIGN_UP";


// sign in with email-
export const REQUEST_SIGN_IN_WITH_EMAIL = "REQUEST_SIGN_IN_WITH_EMAIL";
export const SUCCESS_SIGN_IN_WITH_EMAIL = "SUCCESS_SIGN_IN_WITH_EMAIL";
export const ERROR_SIGN_IN_WITH_EMAIL = "ERROR_SIGN_IN_WITH_EMAIL";